services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:Z
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network  # Add this      

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network  # Add this      

  node:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:Z
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mysql_data:

networks:  
  app-network:
    driver: bridge  
